<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MedEquip.DowntimeHub.Common\MedEquip.DowntimeHub.Common.csproj" />
    <ProjectReference Include="..\MedEquip.DowntimeHub.Model\MedEquip.DowntimeHub.Model.csproj" />
  </ItemGroup>

</Project>
